# -*- coding: utf-8 -*-
"""Auka04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKnlOkKIoOGMDmHcRXG5wn3kaWWRlgE_

Instalando o SDK do Google
"""

!pip install -q -U google-generativeai

# Import the Python SDK
import google.generativeai as genai

GOOGLE_API_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
genai.configure(api_key=GOOGLE_API_KEY)

"""Listar os modelos disponíveis"""

for modelo in genai.list_models():
  if "generateContent" in modelo.supported_generation_methods:
    print(modelo.name)

generation_config = {
    "candidate_count":1,
    "temperature":0.5
}

safety_settings = {
    "HARASSMENT": "BLOCK_NONE",
    "HATE": "BLOCK_NONE",
    "SEXUAL": "BLOCK_NONE",
    "DANGEROUS": "BLOCK_NONE"
}

"""Inicializando o modelo"""

model = genai.GenerativeModel(model_name="gemini-1.0-pro",
                              generation_config=generation_config,
                              safety_settings=safety_settings)

response = model.generate_content("dê sugestões para aprender jenkins, helm e kubernetes gratuitamente")
print(response.text)

chat = model.start_chat(history=[])

prompt = input("Esperando prompt: ")

while prompt != "fim":
  response = chat.send_message(prompt)
  print("Resposta: ", response.text, "\n")
  prompt = input("Esperando prompt: ")